### ISSUE TITLE
remove multiple commands support?

### ISSUE THREAD

**Issue by josedonizetti** [yogthos/migratus#53]
i've seen different complains/issues here about errors due to a migration with multiple commands.
it's good to be able to do it, but as migratus uses SQL commands, and not a DSL. One might add a command with a syntax error. Not a problem if the syntax error is on the first command. But it will leave the DB on a unstable state, if the syntax  error is on the last command, because the first command will be applied, but the migration won't be marked as complete due to the failed last command.

Eg:

- create migration with two commands, last one has a syntax error
- run migrate, and only the first commands create the table, but i get an error and the migration was not marked as executed
- fix the syntax error, and re-run migrate, get an error because the first command was already applied, the table is there already
- try to rollback, but rollback the wrong migration because the one I wanted was not on schema_migrations
- need to go into the database, delete the table by hand, and then be able to run the migration again

On the other side, we also can't mark the migration as completed if both commands haven't succeed, because it will break the rollback if i try to execute it.

I suggest we remove the support for multiple commands, and enforce having one command per migration. I can work on this change, but would like to know what others think about it first?

**Comment by yogthos** [comment]
Personally, I find having multiple commands per file to be very useful. When I have non-trivial migration scenarios it's helpful to see all the steps in a single place. Since it's an opt-in I don't actually see this being a problem as you can choose to have a single migration per file.

Personally, I tend to test the commands using a tool like pgAdmin before using them, which mitigates the problem of syntax errors.

All the commands for each migration file are run as [a single transaction](https://github.com/yogthos/migratus/blob/0b629054e133eb23470c81c9668ae369463d4944/src/migratus/database.clj#L53), so either all commands should succeed or the entire set of migrations rolled back. If there are cases where this isn't happening then it would probably make sense to look as to why that's happening.

**Comment by yogthos** [comment]
I've also just tested the scenario where you have a broken migration using Postgres:

```sql
CREATE TABLE users
(id VARCHAR(20) PRIMARY KEY,
 first_name VARCHAR(30),
 last_name VARCHAR(30),
 email VARCHAR(30),
 admin BOOLEAN,
 last_login TIME,
 is_active BOOLEAN,
 pass VARCHAR(100));
 --;;
 CREATE TABLE borked (id varchar, first_name char
```

The migration fails and no tables are created as would be expected.

**Comment by josedonizetti** [comment]
Not the case for all databases. Postgres provides transaction for DDL commands. But mysql don't, for example.

**Comment by yogthos** [comment]
I think that's really a problem with the database though. I think a warning in the docs about this would be sufficient.

**Comment by yogthos** [comment]
I'm going to close this one. I've added a note about database DDL transaction support in the docs, and I think it should be up to the user to decide whether to use it or not.

**Comment by josedonizetti** [comment]
:+1:
